export {
  auth,
  onAuthStateChanged,
  signInWithGoogle,
  signInWithEmailAndPassword,
  signUpWithEmailAndPassword,
  sendPasswordResetEmail,
  signOut,
  signIn,
  getCurrentUserToken,
  getCurrentUserEmail,
  getCurrentUser,
  setCredentialsPersistance,
  initFirebase,
} from "./auth";
